name: CMake Build & Package

on:
  push:
    tags:
      - 'v*'        # Только при пуше тега v1.0.0 например
  pull_request:
    branches: [ main ] # На PR в main тоже можно билдить для проверки
permissions:
  contents: write    # ← вот это решает ошибку!
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y cmake make g++ rpm

    - name: Configure CMake
      run: cmake -B build

    - name: Build
      run: cmake --build build

    - name: Package DEB
      run: cd build && cpack -G DEB

    - name: Package RPM
      run: cd build && cpack -G RPM

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Packages
        path: |
          build/*.deb
          build/*.rpm

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: Packages
        path: ./artifacts

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: ./artifacts/*
